# Generated by Django 3.0.6 on 2020-06-08 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminSide', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QnA',
            new_name='qa',
        ),
    ]
